version: '3.8'
services:
    php:
        container_name: php
        build:
            context: ./build/php
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ../www:/var/www/html
    nginx:
        container_name: nginx
        build:
            context: ./build/nginx
            dockerfile: Dockerfile
        volumes:
            - ../www:/var/www/html
            - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        ports:
            - "80:80"